name: Run tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get access to repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
